# Generated by Django 6.0.4 on 2026-06-22 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('vehicles', '0003_vehiclemedia_vehicle_cover_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyMeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('make', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('min_year', models.PositiveIntegerField(blank=True, null=True)),
                ('max_price_ngn', models.PositiveBigIntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('feed', 'Feed'), ('whatsapp', 'WhatsApp'), ('call', 'Call'), ('booking', 'Booking'), ('notify_me', 'Notify me')], default='feed', max_length=20)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('inspection', 'Inspection'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('lost', 'Lost')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='dealers.dealer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='dealers.dealerlocation')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dealer', 'stage'], name='leads_lead_dealer__db65f2_idx'), models.Index(fields=['vehicle', 'created_at'], name='leads_lead_vehicle_5d2332_idx')],
            },
        ),
    ]
