# Generated by Django 6.0.4 on 2026-06-23 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_buyerconversation_buyermessage_and_more'),
        ('leads', '0001_initial'),
        ('vehicles', '0003_vehiclemedia_vehicle_cover_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericUploadRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=80)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('s3_key', models.CharField(max_length=500, unique=True)),
                ('public_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('anonymous_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='buyers.buyer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'created_at'], name='leads_analy_name_3a4875_idx')],
            },
        ),
    ]
