import json
from io import BytesIO

from django.db.models import Count, Q
from django.http import FileResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from rest_framework import generics, status, viewsets
from rest_framework.decorators import action
from rest_framework.exceptions import ValidationError
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.common.permissions import IsActiveDealerStaff, has_vehicle_review_permission
from apps.common.views import EnvelopeMixin
from apps.platform.views import HasPlatformCapability, write_audit
from apps.vehicles.models import Vehicle

from .checkout import complete_checkout, handle_charge_success
from .payment_method import (
    complete_payment_method_update,
    handle_payment_method_success,
    start_payment_method_update,
    verification_amount_ngn,
)
from .limits import (
    active_listing_count,
    active_staff_count,
    active_stand_count,
    can_add_stand,
    can_feature_listing,
    can_invite_staff,
    can_publish_listing,
    entitlements_payload,
    featured_used_this_month,
    get_featured_limit,
    get_listing_limit,
    get_staff_limit,
    get_stand_limit,
)
from .models import BillingDispute, BillingPlan, EarlyPlanTermination, Invoice, PaymentEvent, Subscription
from .paystack import (
    billing_callback_url,
    build_checkout_reference,
    is_configured,
    payment_currency,
    public_key,
    verify_webhook_signature,
)
from .plan_catalogue import vat_breakdown
from .subscriptions import (
    apply_due_plan_changes,
    compute_checkout_quote,
    enrol_starter_founding_trial,
    get_active_subscription,
    payment_method_payload,
    pending_downgrade_payload,
    schedule_downgrade,
    trial_billing_payload,
)
from .serializers import (
    BillingDisputeSerializer,
    BillingPlanSerializer,
    CheckoutCompleteSerializer,
    CheckoutSerializer,
    DowngradeRequestSerializer,
    EarlyPlanTerminationSerializer,
    InvoiceSerializer,
    PaymentMethodCompleteSerializer,
    RefundSerializer,
    SubscriptionSerializer,
)


def _format_ngn(amount: int) -> str:
    return f"NGN {int(amount):,}"


def _invoice_pdf(invoice: Invoice) -> BytesIO:
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    dealer_name = invoice.dealer.name if invoice.dealer_id else "Dealer"
    plan_name = invoice.subscription.plan.name if invoice.subscription_id and invoice.subscription else "Subscription"

    pdf.setTitle(f"Invoice {invoice.id}")
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(72, height - 72, "AutoShowroom Invoice")
    pdf.setFont("Helvetica", 10)
    pdf.drawRightString(width - 72, height - 72, f"Invoice ID: {invoice.id}")
    pdf.drawRightString(width - 72, height - 88, f"Issued: {invoice.issued_at:%Y-%m-%d}")

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(72, height - 130, "Bill To")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(72, height - 148, dealer_name)

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(72, height - 210, "Description")
    pdf.drawRightString(width - 72, height - 210, "Amount")
    pdf.line(72, height - 220, width - 72, height - 220)

    tax = vat_breakdown(invoice.amount_ngn)
    amount_ex_vat = invoice.amount_ex_vat_ngn or tax["amountExVatNgn"]
    vat_amount = invoice.vat_ngn or tax["vatNgn"]

    pdf.setFont("Helvetica", 11)
    pdf.drawString(72, height - 245, plan_name)
    pdf.drawRightString(width - 72, height - 245, _format_ngn(invoice.amount_ngn))
    pdf.drawString(72, height - 265, "Amount excluding VAT")
    pdf.drawRightString(width - 72, height - 265, _format_ngn(amount_ex_vat))
    pdf.drawString(72, height - 285, "VAT (7.5%)")
    pdf.drawRightString(width - 72, height - 285, _format_ngn(vat_amount))

    pdf.line(72, height - 305, width - 72, height - 305)
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(72, height - 330, f"Status: {invoice.get_status_display()}")
    pdf.drawRightString(width - 72, height - 330, f"Total (VAT incl.): {_format_ngn(invoice.amount_ngn)}")

    pdf.setFont("Helvetica", 9)
    pdf.drawString(72, 72, "Generated by AutoShowroom. Prices include VAT at 7.5%.")
    pdf.showPage()
    pdf.save()
    buffer.seek(0)
    return buffer


class BillingPlansView(EnvelopeMixin, generics.ListAPIView):
    permission_classes = [AllowAny]
    serializer_class = BillingPlanSerializer

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return BillingPlan.objects.filter(is_active=True)


class BillingSummaryView(EnvelopeMixin, APIView):
    permission_classes = [IsActiveDealerStaff]

    def get(self, request):
        dealer = request.user.dealer
        apply_due_plan_changes(dealer)
        enrol_starter_founding_trial(dealer)
        subscription = get_active_subscription(dealer)
        listing_limit = get_listing_limit(dealer)
        staff_limit = get_staff_limit(dealer)
        featured_limit = get_featured_limit(dealer)
        featured_used = featured_used_this_month(dealer)
        plan = subscription.plan if subscription else None
        return Response(
            {
                "planId": (plan.id if plan else dealer.plan_id),
                "subscription": SubscriptionSerializer(subscription).data if subscription else None,
                "pendingDowngrade": pending_downgrade_payload(subscription),
                "paymentMethod": payment_method_payload(subscription),
                "trial": trial_billing_payload(subscription),
                "listingLimit": listing_limit,
                "activeListings": active_listing_count(dealer),
                "canPublish": can_publish_listing(dealer),
                "standLimit": get_stand_limit(dealer),
                "standCount": active_stand_count(dealer),
                "canAddStand": can_add_stand(dealer),
                "staffLimit": staff_limit,
                "staffCount": active_staff_count(dealer),
                "canInviteStaff": can_invite_staff(dealer),
                "featuredLimit": featured_limit,
                "featuredUsed": featured_used,
                "canFeature": can_feature_listing(dealer),
                "entitlements": entitlements_payload(dealer),
                "vehicleCount": Vehicle.objects.filter(dealer=dealer).count(),
            }
        )


class InvoiceListView(EnvelopeMixin, generics.ListAPIView):
    permission_classes = [IsActiveDealerStaff]
    serializer_class = InvoiceSerializer

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Invoice.objects.select_related("dealer", "subscription")
        if has_vehicle_review_permission(self.request.user):
            dealer_id = self.request.query_params.get("dealerId")
            return queryset.filter(dealer_id=dealer_id) if dealer_id else queryset
        return queryset.filter(dealer_id=self.request.user.dealer_id)


class InvoiceDetailView(EnvelopeMixin, generics.RetrieveAPIView):
    permission_classes = [IsActiveDealerStaff]
    serializer_class = InvoiceSerializer
    lookup_url_kwarg = "invoice_id"

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Invoice.objects.select_related("dealer", "subscription")
        if has_vehicle_review_permission(self.request.user):
            return queryset
        return queryset.filter(dealer_id=self.request.user.dealer_id)


class InvoicePdfView(EnvelopeMixin, APIView):
    permission_classes = [IsActiveDealerStaff]

    def get(self, request, invoice_id):
        queryset = Invoice.objects.select_related("dealer", "subscription__plan")
        if not has_vehicle_review_permission(request.user):
            queryset = queryset.filter(dealer_id=request.user.dealer_id)
        invoice = get_object_or_404(queryset, id=invoice_id)
        filename = f"autoshowroom-invoice-{invoice.issued_at:%Y%m%d}-{str(invoice.id)[:8]}.pdf"
        return FileResponse(
            _invoice_pdf(invoice),
            as_attachment=True,
            filename=filename,
            content_type="application/pdf",
        )


class CheckoutView(EnvelopeMixin, APIView):
    permission_classes = [IsActiveDealerStaff]

    def post(self, request):
        serializer = CheckoutSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        dealer = request.user.dealer
        plan = get_object_or_404(BillingPlan, id=serializer.validated_data["planId"], is_active=True)
        billing_interval = serializer.validated_data.get("billingInterval") or "monthly"
        active = get_active_subscription(dealer)

        if (
            active
            and dealer.plan_id == plan.id
            and active.billing_interval == billing_interval
            and active.status != Subscription.Status.TRIALING
        ):
            raise ValidationError("You are already on this plan.")

        quote = compute_checkout_quote(dealer, plan, billing_interval=billing_interval)
        reference = build_checkout_reference(dealer.id, plan.id)
        callback_url = f"{billing_callback_url()}?checkout={reference}"
        amount_kobo = quote["amount_kobo"]
        amount_ngn = quote["amount_ngn"]
        tax = vat_breakdown(quote["list_price_ngn"])

        init_payload = {
            "dealerId": str(dealer.id),
            "planId": plan.id,
            "amountNgn": amount_ngn,
            "amountKobo": amount_kobo,
            "listPriceNgn": quote["list_price_ngn"],
            "creditAppliedNgn": quote["credit_applied_ngn"],
            "checkoutKind": quote["checkout_kind"],
            "billingInterval": billing_interval,
            "foundingTrial": quote.get("founding_trial", False),
            "trialDays": quote.get("trial_days", 0),
            "preservePeriodEnd": (
                quote["preserve_period_end"].isoformat()
                if quote["preserve_period_end"]
                else None
            ),
        }

        if amount_ngn <= 0:
            PaymentEvent.objects.create(
                event_type="checkout.initiated",
                reference=reference,
                payload={**init_payload, "fullyCovered": True},
            )
            return Response(
                {
                    "planId": plan.id,
                    "reference": reference,
                    "fullyCovered": True,
                    "publicKey": public_key(),
                    "amountNgn": amount_ngn,
                    "listPriceNgn": quote["list_price_ngn"],
                    "creditAppliedNgn": quote["credit_applied_ngn"],
                    "checkoutKind": quote["checkout_kind"],
                    "billingInterval": billing_interval,
                    "foundingTrial": quote.get("founding_trial", False),
                    "trialDays": quote.get("trial_days", 0),
                    "vatNgn": tax["vatNgn"],
                    "amountExVatNgn": tax["amountExVatNgn"],
                },
                status=status.HTTP_201_CREATED,
            )

        if not is_configured():
            raise ValidationError("Paystack is not configured. Contact support.")

        PaymentEvent.objects.create(
            event_type="checkout.initiated",
            reference=reference,
            payload=init_payload,
        )

        return Response(
            {
                "planId": plan.id,
                "reference": reference,
                "fullyCovered": False,
                "publicKey": public_key(),
                "email": request.user.email,
                "amountNgn": amount_ngn,
                "amountKobo": amount_kobo,
                "listPriceNgn": quote["list_price_ngn"],
                "creditAppliedNgn": quote["credit_applied_ngn"],
                "checkoutKind": quote["checkout_kind"],
                "billingInterval": billing_interval,
                "foundingTrial": quote.get("founding_trial", False),
                "trialDays": quote.get("trial_days", 0),
                "vatNgn": tax["vatNgn"],
                "amountExVatNgn": tax["amountExVatNgn"],
                "currency": payment_currency(),
                "callbackUrl": callback_url,
                "metadata": {
                    "dealer_id": str(dealer.id),
                    "plan_id": plan.id,
                    "expected_amount_kobo": amount_kobo,
                    "checkout_kind": quote["checkout_kind"],
                    "billing_interval": billing_interval,
                },
            },
            status=status.HTTP_201_CREATED,
        )


class CheckoutCompleteView(EnvelopeMixin, APIView):
    permission_classes = [IsActiveDealerStaff]

    def post(self, request):
        serializer = CheckoutCompleteSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        dealer = request.user.dealer
        plan = get_object_or_404(BillingPlan, id=serializer.validated_data["planId"], is_active=True)
        reference = serializer.validated_data.get("reference", "").strip()
        if not reference:
            raise ValidationError("Payment reference is required.")

        result = complete_checkout(dealer, plan, reference)
        return Response(result, status=status.HTTP_201_CREATED)


class DowngradeRequestView(EnvelopeMixin, APIView):
    permission_classes = [IsActiveDealerStaff]

    def post(self, request):
        serializer = DowngradeRequestSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        dealer = request.user.dealer
        target_plan = get_object_or_404(
            BillingPlan,
            id=serializer.validated_data["targetPlanId"],
            is_active=True,
        )
        result = schedule_downgrade(
            dealer,
            target_plan,
            reason=serializer.validated_data.get("reason", ""),
        )
        return Response(result, status=status.HTTP_201_CREATED)


class PaymentMethodUpdateView(EnvelopeMixin, APIView):
    permission_classes = [IsActiveDealerStaff]

    def post(self, request):
        if not is_configured():
            raise ValidationError("Paystack is not configured. Contact support.")

        dealer = request.user.dealer
        session = start_payment_method_update(dealer, request.user.email)
        callback_url = f"{billing_callback_url()}?cardUpdate={session['reference']}"

        return Response(
            {
                "reference": session["reference"],
                "publicKey": public_key(),
                "email": session["email"],
                "amountNgn": session["amountNgn"],
                "amountKobo": session["amountKobo"],
                "verificationAmountNgn": verification_amount_ngn(),
                "currency": payment_currency(),
                "callbackUrl": callback_url,
                "metadata": session["metadata"],
            },
            status=status.HTTP_201_CREATED,
        )


class PaymentMethodCompleteView(EnvelopeMixin, APIView):
    permission_classes = [IsActiveDealerStaff]

    def post(self, request):
        serializer = PaymentMethodCompleteSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        dealer = request.user.dealer
        reference = serializer.validated_data["reference"].strip()
        result = complete_payment_method_update(dealer, reference)
        return Response(result, status=status.HTTP_201_CREATED)


class PaystackWebhookView(EnvelopeMixin, APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        signature = request.headers.get("X-Paystack-Signature", "")
        if not verify_webhook_signature(request.body, signature):
            return Response({"error": "Invalid signature"}, status=status.HTTP_400_BAD_REQUEST)

        try:
            payload = json.loads(request.body.decode("utf-8"))
        except json.JSONDecodeError as exc:
            raise ValidationError("Invalid webhook payload.") from exc

        event_type = payload.get("event", "unknown")
        data = payload.get("data") or {}
        reference = data.get("reference", "")

        event = PaymentEvent.objects.create(
            provider="paystack",
            event_type=f"paystack.{event_type}",
            reference=reference,
            payload=payload,
        )

        if event_type == "charge.success":
            metadata = data.get("metadata") or {}
            if metadata.get("purpose") == "payment_method_update":
                handle_payment_method_success(reference, metadata)
            else:
                handle_charge_success(reference, metadata)
        elif event_type == "charge.failed":
            metadata = data.get("metadata") or {}
            dealer_id = metadata.get("dealer_id")
            plan_id = metadata.get("plan_id")
            if dealer_id and plan_id:
                from apps.dealers.models import Dealer
                from apps.notifications.services import notify_payment_failed

                dealer = Dealer.objects.filter(id=dealer_id).first()
                plan = BillingPlan.objects.filter(id=plan_id).first()
                if dealer and plan:
                    notify_payment_failed(
                        dealer,
                        plan_name=plan.name,
                        amount_ngn=plan.price_ngn,
                        failure_reason=data.get("gateway_response") or data.get("message") or "Payment failed.",
                        reference=reference,
                    )

        return Response({"eventId": str(event.id)}, status=status.HTTP_202_ACCEPTED)


class PlatformBillingConfigView(EnvelopeMixin, APIView):
    permission_classes = [HasPlatformCapability]
    required_capability = "billing.read"

    def get(self, request):
        active_subscriptions = Subscription.objects.filter(status=Subscription.Status.ACTIVE).select_related("plan")
        return Response(
            {
                "activePlans": BillingPlan.objects.filter(is_active=True).count(),
                "subscriptions": Subscription.objects.count(),
                "activeSubscriptions": active_subscriptions.count(),
                "monthlyRecurringRevenue": sum(subscription.plan.price_ngn for subscription in active_subscriptions),
                "openDisputes": BillingDispute.objects.filter(status=BillingDispute.Status.OPEN).count(),
            }
        )


class PlatformBillingPlanViewSet(EnvelopeMixin, viewsets.ModelViewSet):
    permission_classes = [HasPlatformCapability]
    read_capability = "billing.read"
    write_capability = "billing.write"
    serializer_class = BillingPlanSerializer
    queryset = BillingPlan.objects.annotate(
        activeDealerCount=Count("subscriptions", filter=Q(subscriptions__status=Subscription.Status.ACTIVE))
    )
    http_method_names = ["get", "post", "patch", "delete", "head", "options"]

    def perform_create(self, serializer):
        plan = serializer.save()
        write_audit(self.request.user, "billing_plan.created", plan)

    def perform_update(self, serializer):
        plan = serializer.save()
        write_audit(self.request.user, "billing_plan.updated", plan)


class PlatformSubscriptionViewSet(EnvelopeMixin, viewsets.ReadOnlyModelViewSet):
    permission_classes = [HasPlatformCapability]
    read_capability = "billing.read"
    write_capability = "billing.write"
    serializer_class = SubscriptionSerializer
    queryset = Subscription.objects.select_related("dealer", "plan")

    @action(detail=True, methods=["post"], url_path="refund")
    def refund(self, request, pk=None):
        subscription = self.get_object()
        serializer = RefundSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        event = PaymentEvent.objects.create(
            event_type="subscription.refund_requested",
            reference=str(subscription.id),
            payload=serializer.validated_data,
        )
        write_audit(request.user, "subscription.refund_requested", subscription)
        return Response({"eventId": str(event.id)}, status=status.HTTP_202_ACCEPTED)

    @action(detail=False, methods=["get"], url_path="stats")
    def stats(self, request):
        return Response(
            {
                "total": Subscription.objects.count(),
                "byStatus": list(Subscription.objects.values("status").annotate(count=Count("id"))),
            }
        )


class PlatformBillingDisputeViewSet(EnvelopeMixin, viewsets.ModelViewSet):
    permission_classes = [HasPlatformCapability]
    read_capability = "billing.read"
    write_capability = "billing.write"
    serializer_class = BillingDisputeSerializer
    queryset = BillingDispute.objects.select_related("dealer", "invoice")
    http_method_names = ["get", "post", "patch", "head", "options"]

    @action(detail=True, methods=["post"], url_path="accept")
    def accept(self, request, pk=None):
        dispute = self.get_object()
        dispute.status = BillingDispute.Status.ACCEPTED
        dispute.save(update_fields=["status", "updated_at"])
        write_audit(request.user, "billing_dispute.accepted", dispute)
        return Response(self.get_serializer(dispute).data)

    @action(detail=True, methods=["post"], url_path="decline")
    def decline(self, request, pk=None):
        dispute = self.get_object()
        dispute.status = BillingDispute.Status.DECLINED
        dispute.save(update_fields=["status", "updated_at"])
        write_audit(request.user, "billing_dispute.declined", dispute)
        return Response(self.get_serializer(dispute).data)

    @action(detail=True, methods=["patch"], url_path="note")
    def note(self, request, pk=None):
        dispute = self.get_object()
        dispute.note = request.data.get("note", dispute.note)
        dispute.save(update_fields=["note", "updated_at"])
        write_audit(request.user, "billing_dispute.note_updated", dispute)
        return Response(self.get_serializer(dispute).data)

    @action(detail=True, methods=["post"], url_path="upload-url")
    def upload_url(self, request, pk=None):
        dispute = self.get_object()
        return Response({"disputeId": str(dispute.id), "uploadUrl": None})

    @action(detail=False, methods=["get"], url_path="stats")
    def stats(self, request):
        return Response(
            {
                "total": BillingDispute.objects.count(),
                "byStatus": list(BillingDispute.objects.values("status").annotate(count=Count("id"))),
            }
        )

    @action(detail=False, methods=["get"], url_path="sla")
    def sla(self, request):
        return Response({"openDisputes": BillingDispute.objects.filter(status=BillingDispute.Status.OPEN).count()})


class PlatformEarlyPlanTerminationViewSet(EnvelopeMixin, viewsets.ModelViewSet):
    permission_classes = [HasPlatformCapability]
    read_capability = "billing.read"
    write_capability = "billing.write"
    serializer_class = EarlyPlanTerminationSerializer
    queryset = EarlyPlanTermination.objects.select_related("dealer", "subscription", "plan")

    @action(detail=True, methods=["post"], url_path="approve")
    def approve(self, request, pk=None):
        termination = self.get_object()
        termination.status = EarlyPlanTermination.Status.APPROVED
        termination.decision_note = request.data.get("note", "")
        termination.decided_at = timezone.now()
        termination.save(update_fields=["status", "decision_note", "decided_at"])
        write_audit(request.user, "early_termination.approved", termination, {"note": termination.decision_note})
        return Response(self.get_serializer(termination).data)

    @action(detail=True, methods=["post"], url_path="decline")
    def decline(self, request, pk=None):
        termination = self.get_object()
        termination.status = EarlyPlanTermination.Status.DECLINED
        termination.decision_note = request.data.get("note", "")
        termination.decided_at = timezone.now()
        termination.save(update_fields=["status", "decision_note", "decided_at"])
        write_audit(request.user, "early_termination.declined", termination, {"note": termination.decision_note})
        return Response(self.get_serializer(termination).data)
