# Generated by Django 6.0.4 on 2026-06-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_buyerconversation_buyermessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerotp',
            name='name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
