# Generated by Django 6.0.4 on 2026-06-22 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('vehicles', '0003_vehiclemedia_vehicle_cover_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=160)),
                ('buyer_phone', models.CharField(max_length=32)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending_otp', 'Pending OTP'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='pending_otp', max_length=20)),
                ('otp_code', models.CharField(max_length=8)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('scheduled_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dealers.dealer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='dealers.dealerlocation')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
