# Generated by Django 6.0.4 on 2026-06-22 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('buyers', '0001_initial'),
        ('dealers', '0001_initial'),
        ('vehicles', '0003_vehiclemedia_vehicle_cover_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='buyers.buyer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='dealers.dealer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='dealers.dealerlocation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='bookings.booking'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['dealer', 'status'], name='bookings_bo_dealer__e28fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle', 'scheduled_at'], name='bookings_bo_vehicle_8f3195_idx'),
        ),
    ]
