# Generated by Django 6.0.4 on 2026-06-23 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerVerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('cac', 'CAC'), ('tax', 'Tax'), ('identity', 'Identity'), ('premises', 'Premises'), ('other', 'Other')], default='other', max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('file_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='dealers.dealer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
